version: '3.0'

services:
  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: app
    networks:
      - goforum_network
    volumes:
      - ./:/app
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - goforum_network
    depends_on:
      - app

networks:
  goforum_network:
    name: goforum_network
    driver: bridge
